### ISSUE TITLE
Cyber4S Community

### ISSUE THREAD

**Issue by AlonBru** [ItsDrTsach/together-we-strong-c4s#8]
please move the Cyber4S communities from under https://github.com/ItsDrTsach/together-we-strong-c4s/blob/master/resources/links.md
to the main readme,
alse-please add a link to the facebook group.
when you make a pull request to fix this issue please [link it to this issue](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue)

**Comment by ItsDrTsach** [comment]
i added a Facebook link, forgot to link it to that issue though...
